### ISSUE TITLE
Unfork from 18F/handbook to enable search from Github UI

### ISSUE THREAD

**Issue by kevwalsh** [CivicActions/guidebook#660]
![image](https://user-images.githubusercontent.com/643678/100802125-f4628200-33f6-11eb-895f-3362e6891af4.png)

Not a huge deal, but we can't perform searches on forked repos from the github UI. 

Known workarounds: 
1. [search in gitlab](https://gitlab.com/search?utf8=%E2%9C%93&search=security&group_id=6721510&project_id=17740908&scope=&search_code=true&snippets=false&repository_ref=master&nav_source=navbar)
2. [search in RTD](https://handbook.civicactions.com/en/latest/search.html?q=security)

**Comment by dmundra** [comment]
@grugnog looks like the virtual assistant in GitHub will do this for you according to stackoverflow https://stackoverflow.com/questions/38831301/how-to-un-fork-the-github-repository/66470086#66470086

Original solution is a destructive solution but maybe the virtual assistant is not? Do this 👍🏾  or 👎🏾 ?

**Comment by grugnog** [comment]
Nice find @dmundra! I submitted this as a request through the virtual assistant

**Comment by dmundra** [comment]
Thanks @grugnog. Search works now: https://github.com/CivicActions/handbook/search?q=security
