### ISSUE TITLE
The handbook sitemap.xml is referencing branches, causing broken links in google search

### ISSUE THREAD

**Issue by dmundra** [CivicActions/guidebook#686]
A random issue I stumbled upon. It appears that the sitemap.xml (https://handbook.civicactions.com/sitemap.xml) for the handbook is only listing links to various branches. I am guessing that Google is then indexing the pages from that link and generating links that no longer work.

An example of the issue (worked on Jan 29, 2021):
- Search for site:civicactions.com agile
- The first result is the page with the title 'Agile Overview - CivicActions Handbook'.
- The URL is https://handbook.civicactions.com/en/akaroleff-patch-4/04-how-we-work/agile-overview/ which does not load.

Probably best would be that the sitemap.xml does not include branches and if possible include all actual pages under the latest branch.

**Comment by grugnog** [comment]
This sitemap is managed by readthedocs and I don't think we can update/disable it directly. We could disable rtd-bot, which spins these review environments up/down, although they can be helpful at times. https://stackoverflow.com/posts/63581610/revisions does has an alternate approach we could explore also.

**Comment by dmundra** [comment]
I think the review environments are definitely useful. Nice find on the stackoverflow. I looked at https://handbook.civicactions.com/robots.txt and see that it is already disallowing those review environments so I wonder why Google indexed the older ones. More research I guess to figure out the cause.

**Comment by grugnog** [comment]
@dmundra I manually hid those environments earlier to see what that would do, so I think that does work but isn't a long term solution - I am not sure if there is a way we can make the rtd-bot hide these by default - that could work?

**Comment by dmundra** [comment]
@grugnog I couldn't find much documentation on rtd-bot configuration or anything related to rtd-bot. My google-fu is low on that one.

The RTD documentation mentions exactly what you saw with the sitemap.xml so maybe following the StackOverflow answer and provide [a custom robots.txt file that denies all and only allows only the latest URL](https://docs.readthedocs.io/en/stable/guides/technical-docs-seo-guide.html?highlight=robots.txt#use-a-robots-txt-file). Thoughts?

**Comment by dmundra** [comment]
Updated robots.txt to let Google know to ignore other branches: https://handbook.civicactions.com/en/latest/README/robots.txt
