### ISSUE TITLE
Mark GitHub repo "releases" for significant changes to the handbook 

### ISSUE THREAD

**Issue by joduinn** [CivicActions/guidebook#730]
When significant changes are made to the handbook, can it be tagged as a new release/version? For added goodness, have the creation of the new release be posted to slack so people know to look for the changes.

I ask because right now, there is no way to know when (like say the changing to the current-events channel or more recently, the new tech reimbursement policy). I've found out about some changes that were officially live in the handbook only after being verbally told of them... even though I had already heard in AHC that they were "being worked on". This has happened to me multiple times, most recently this week about the tech stipend. 

Following the GitHub repo for changes is too noisy, as there are so many other changes for typos and smaller non-significant changes. In GitHub, when following a repo, you can choose to only be notified of "releases". This would be perfect. But it requires a human to tag a new release - and it looks like we have not done this. 

Not sure who to ask, hence creating this issue to track.

**Comment by grugnog** [comment]
I made an initial v1.0 release and configured Slack to post (only) these to #announcements
